Try and fix race condition on travis
Seems to stem from Attribute being created and put into the tree before
set_parent is called. Put some debugging in to try and diagnose it if this
happens, but re-arranging set_parent in children should help

======================================================================
FAIL: test_server_with_malcolm_client (tests.test_comms.test_websocket.test_system_websocket.TestSystemWSCommsServerAndClient)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/dls-controls/pymalcolm/tests/test_comms/test_websocket/test_system_websocket.py", line 95, in test_server_with_malcolm_client
    futures = task.when_matches(self.block2["state"], "Ready")
  File "/home/travis/build/dls-controls/pymalcolm/malcolm/core/task.py", line 111, in when_matches
    attr, self._match_update, f, value, subscription_ids)
  File "/home/travis/build/dls-controls/pymalcolm/malcolm/core/task.py", line 160, in subscribe
    request = Subscribe(None, self.q, endpoint, False)
  File "/home/travis/build/dls-controls/pymalcolm/malcolm/core/request.py", line 164, in __init__
    self.set_endpoint(endpoint)
  File "/home/travis/build/dls-controls/pymalcolm/malcolm/core/request.py", line 189, in set_endpoint
    endpoint = [deserialize_object(e, base_string) for e in endpoint]
  File "/home/travis/build/dls-controls/pymalcolm/malcolm/core/serializable.py", line 25, in deserialize_object
    "Expected %s, got %r" % (type_check, ob)
AssertionError: Expected <type 'basestring'>, got None